import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Navigation from "@/components/Navigation";
import { getNavigationData } from "./actions/categories";
import { getSetting } from "./actions/settings";
import AnnouncementHeader from "@/components/AnnouncementHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [navigationData, announcementHtml] = await Promise.all([
    getNavigationData(),
    getSetting("announcement_bar_html"),
  ]);
  return (
    <html lang="en">
      <body className={inter.className}>
        {announcementHtml && <AnnouncementHeader htmlContent={announcementHtml} />}
        <Header>
          <Navigation navigationData={navigationData} />
        </Header>
        <main className="pt-8">{children}</main>
      </body>
    </html>
  );
}
