import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Navigation from "@/components/Navigation";
import { getNavigationData } from "@/app/actions/categoryActions";
import { getSetting } from "./actions/settings";
import AnnouncementHeader from "@/components/AnnouncementHeader";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [
    navigationData,
    announcementHtml,
    announcementDismissible,
    isHeaderSticky,
  ] = await Promise.all([
    getNavigationData(),
    getSetting("announcement_bar_html"),
    getSetting("announcement_dismissible"),
    getSetting("sticky_header").then((val) => val === "true"),
  ]);

  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} flex flex-col h-full`}>
        {announcementHtml && (
          <AnnouncementHeader
            htmlContent={announcementHtml}
            isDismissible={announcementDismissible === "true"}
          />
        )}
        <Header isSticky={isHeaderSticky} />
        <Navigation navigationData={navigationData} />
        <main className="flex-grow pb-12">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
